### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ericnyamu** [Naguissa/WiFiLib#1]
Is there away to load balance between two wifi connections on an android phone ?Imagine being at the CBD (central business districts)with all the free open public wifi.wouldn't it be of tremendous advantage to connect to two or even three one wifi networks and load balance the internet connection?If it can be done with a lan setup am sure it can also be done on public wifi using an android phone.
the best way to achieve load balancing on android is to have two network interfaces.the real one and the virtual one. and have then connect to two different networks at the same time.the second network interface which is a virtual one will be created and connects to free wifi network just like the fast one.

**Comment by Naguissa** [comment]
I'm testing this with a Maple Mini clone microntroller and I can assure you don't need load balancing: even with this more-or-less powerful microcontroller it's a pain in the ass transmit large amount of data (10Kb is 'large' for this piece).

And, because communication, you cannot transmit binary data, only characters (base64 does the trick for using binaries).

I think you can program ESP directly and bypass these limitations, but then you may use a ESP201 in order to get a lot of I/Os, and maybe even that is short for some projects.



About your question, maybe I'm wrong but I suppose that if you want to balance between networks you need to be connected on all of them, so using 2 Wifi networks suppose to have 2 wifi chips or, at least, one that can handle several connections. And that's not the common case...

**Comment by Naguissa** [comment]
Closing due spam and out of scope
